permitiendo clonar múltiples repositorios a la vez...

diff --git a/lorebi-git b/lorebi-git
--- a/lorebi-git
+++ b/lorebi-git
@@ -287,15 +287,10 @@ elif [[ $option = "3" ]]; then
 	done
 
 	printf "\n ${CYAN}${BOLD}Seleccione un repositorio:${WHITE} "
-	read -p "" repoSelec
+	read -p "" -a repoSelec
 	printf "\n"
  
-    if [[ $repoSelec -ge ${#array[*]} || $repoSelec < 0 || !($repoSelec =~ $isNumber) || $repoSelec = "" ]]; then
-		printf "\n${RED}${BOLD} Debe seleccionar un repositorio...${NC}\n\n"
-		exit 1
-	fi
-
-   	repository=${array[$repoSelec]}
+   	repository="clone"
 fi
 
 ##############################################################
@@ -371,50 +366,63 @@ if [[ $option = "2" ]]; then
 
 elif [[ $option = "3" ]]; then
 
-	direc=$(pwd)"/"${repository:0:-4}
-	printf " $1${BOLD}${YELLOW}Está seguro de clonar ${I}'${array[$repoSelec]}' ${NF}${YELLOW}${BOLD}en ${I}'$direc'${BOLD}? [Y/n/o]: ${WHITE}"
-	read -n 1 choice
-	printf "${NC}\n"
+	for repo in ${repoSelec[@]}; do
 
-	if [[ $choice = "o" || $choice = "O" ]]; then
-		whereDoICLone
-	elif [[ $choice != "Y" && $choice != "y" && $choice != "" ]]; then
-		printf "\n\n${GREEN} ${BOLD}Operación abortada... ${NC}\n\n"
-		exit 1
-	else 
-		choice=""
-	fi
-
-	allClear=false
-	while [[ $allClear = false ]]; do
-		if [[ -d $direc ]]; then
-			confirm "${YELLOW}" "Ya existe el directorio ${I}'$direc'... Clonar en uno distinto"
-			whereDoICLone
-		else
-			allClear=true
+		if [[ !($repo =~ $isNumber) || $repo -ge ${#array[*]} || $repo < 0 || $repo = "" ]]; then
+			printf "\n${RED}${BOLD} El repositorio número: '$repo' no existe...${NC}\n\n"
+			exit 1
 		fi
+
+		repository=${array[$repo]}
+
+		direc=$(pwd)"/"${repository:0:-4}
+		printf " $1${BOLD}${YELLOW}Está seguro de clonar ${I}'${array[$repo]}' ${NF}${YELLOW}${BOLD}en ${I}'$direc'${BOLD}? [Y/n/o]: ${WHITE}"
+		read -n 1 choice
+		printf "${NC}\n"
+
+		if [[ $choice = "o" || $choice = "O" ]]; then
+			whereDoICLone
+		elif [[ $choice != "Y" && $choice != "y" && $choice != "" ]]; then
+			printf "\n\n${GREEN} ${BOLD}Operación abortada... ${NC}\n\n"
+			exit 1
+		else 
+			choice=""
+		fi
+
+		allClear=false
+		while [[ $allClear = false ]]; do
+			if [[ -d $direc ]]; then
+				confirm "${YELLOW}" "Ya existe el directorio ${I}'$direc'... Clonar en uno distinto"
+				whereDoICLone
+			else
+				allClear=true
+			fi
+		done
+
+		printf "\n${CYAN}${BOLD} Clonando repositorio...${NC}\n\n"
+
+		git clone git+ssh://$SERVER:$PORT$REPOS_PATH$repository $choice
+		$(ssh -t -t -o ConnectTimeout=10 -o StrictHostKeyChecking=no $SERVER -p $PORT "$(declare -f); logger CLONE ${repository} $USERIP $USER $USERHOME");
+		cd $direc
+		git remote rename origin $REMOTE_NAME
+
+		# C R E A N D O   Y   A C T U A L I Z A N D O   
+		# T O D A S   L A S   R A M A S   R E M O T A S
+		branches=$(git branch -a | grep remotes/$REMOTE_NAME | grep -v HEAD | grep -v master)
+
+		cont=0
+		for remote in ${branches[*]}; do
+			IFS='/' read -r -a branch <<< "$remote"
+			printf "\n${CYAN}${BOLD} Creando y actualizando rama remota: ${YELLOW}${branch[2]} ${NC}\n\n"
+			git branch ${branch[2]} $remote
+
+			let cont+=1
+		done
+
+		printf "\n\n"
+		cd ..
 	done
 
-	printf "\n${CYAN}${BOLD} Clonando repositorio...${NC}\n\n"
-
-	git clone git+ssh://$SERVER:$PORT$REPOS_PATH$repository $choice
-	$(ssh -t -t -o ConnectTimeout=10 -o StrictHostKeyChecking=no $SERVER -p $PORT "$(declare -f); logger CLONE ${repository} $USERIP $USER $USERHOME");
-	cd $direc
-	git remote rename origin $REMOTE_NAME
-
-	# C R E A N D O   Y   A C T U A L I Z A N D O   
-	# T O D A S   L A S   R A M A S   R E M O T A S
-	branches=$(git branch -a | grep remotes/$REMOTE_NAME | grep -v HEAD | grep -v master)
-
-	cont=0
-	for remote in ${branches[*]}
-	do
-		IFS='/' read -r -a branch <<< "$remote"
-		printf "\n${CYAN}${BOLD} Creando y actualizando rama remota: ${YELLOW}${branch[2]} ${NC}\n\n"
-		git branch ${branch[2]} $remote
-
-		let cont+=1
-	done
 elif [[ $option = "4" ]]; then
 	validatePackage git
 	saveScript
